#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.xz"
MD5SUMLIST="53f38e7591fa57c3d2cee682be668e5b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's:/\\\${:/\\\$\\{:' bin/automake.in

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.16.1

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

