#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz"
MD5SUMLIST="00fce8de158422f5ccd2666512329bd2"

###################################################
preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
###################################################

cp -v configure{,.orig}
sed 's:/usr/local/bin:/bin:' configure.orig > configure

./configure --prefix=/tools       \
            --with-tcl=/tools/lib \
            --with-tclinclude=/tools/include

make

make SCRIPTS="" install

#################
} # END OF FILE #
#################

