#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-4.16.tar.xz"
MD5SUMLIST="ad9f1ff81276fe8d90d077484d6d4b5e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

