#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.2.tar.xz"
MD5SUMLIST="0524258861f00be1a02d27d39d8e5e62"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/fuser   ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/killall ${FAKEROOT}/bin

#################
} # END OF FILE #
#################

