#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.93.tar.xz
          http://www.linuxfromscratch.org/patches/lfs/8.4/sysvinit-2.93-consolidated-1.patch"
MD5SUMLIST="041dbe36a5dd80b2108aff305bc10620
            aaa84675e717504d7d3da452c8c2eaf1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../sysvinit-2.93dsf-consolidated-1.patch

make -C src

make ROOT=${FAKEROOT} -C src install

#################
} # END OF FILE #
#################

