#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://downloads.sourceforge.net/tcl/tcl8.6.9-src.tar.gz"
MD5SUMLIST="aa0a121d95a0e7b73a036f26028538d4"

###################################################
preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
###################################################

cd unix
./configure --prefix=/tools

make

make install

chmod -v u+w /tools/lib/libtcl8.6.so

make install-private-headers

ln -sv tclsh8.6 /tools/bin/tclsh

#################
} # END OF FILE #
#################

